import gzip                                                                                                                                                                                                         
import json                                                                                                                                                                                                         
import shutil                                                                                                                                                                                                       
import tarfile                                                                                                                                                                                                      
from pathlib import Path                                                                                                                                                                                            
                                                                                                                                                                                                                    
import arxiv                                                                                                                                                                                                        
                                                                                                                                                                                                                    
from src.config import load_config, RAW_DIR, METADATA_DIR                                                                                                                                                           
                
                                                                                                                                                                                                                    
SAFE_EXTENSIONS = {".tex", ".bib", ".bbl", ".sty", ".cls", ".bst"}
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def is_gzip(filepath):
    with open(filepath, "rb") as f:                                                                                                                                                                                 
        return f.read(2) == b"\x1f\x8b"                                                                                                                                                                             
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def extract_source(source_file, paper_dir):                                                                                                                                                                         
    """Extract LaTeX source from arXiv download (tar.gz, gzip, or raw tex)."""                                                                                                                                      
    source_file = Path(source_file)                                                                                                                                                                                 
                                                                                                                                                                                                                    
    if tarfile.is_tarfile(source_file):                                                                                                                                                                             
        with tarfile.open(source_file) as tar:                                                                                                                                                                      
            safe_members = [                                                                                                                                                                                        
                member for member in tar.getmembers()                                                                                                                                                               
                if member.isfile()                                                                                                                                                                                  
                and Path(member.name).suffix in SAFE_EXTENSIONS                                                                                                                                                     
            ]                                                                                                                                                                                                       
            tar.extractall(path=paper_dir, members=safe_members)                                                                                                                                                    
        source_file.unlink()                                                                                                                                                                                        
                                                                                                                                                                                                                    
    elif is_gzip(source_file):                                                                                                                                                                                      
        try:                                                                                                                                                                                                        
            with gzip.open(source_file, "rb") as gz:                                                                                                                                                                
                content = gz.read()                                                                                                                                                                                 
            (paper_dir / "main.tex").write_bytes(content)                                                                                                                                                           
            source_file.unlink()                                                                                                                                                                                    
        except Exception:                                                                                                                                                                                           
            source_file.rename(paper_dir / "main.tex")                                                                                                                                                              
    else:                                                                                                                                                                                                           
        source_file.rename(paper_dir / "main.tex")
                                                                                                                                                                                                                    
    tex_files = list(paper_dir.rglob("*.tex"))                                                                                                                                                                      
    return len(tex_files) > 0                                                                                                                                                                                       
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def download_paper(result, paper_dir):                                                                                                                                                                              
    """Download and extract LaTeX source for one paper."""                                                                                                                                                          
    paper_dir.mkdir(parents=True, exist_ok=True)                                                                                                                                                                    
                                                                                                                                                                                                                    
    try:                                                                                                                                                                                                            
        source_path = result.download_source(                                                                                                                                                                       
            dirpath=str(paper_dir), filename="source"                                                                                                                                                               
        )                                                                                                                                                                                                           
    except Exception as error:                                                                                                                                                                                      
        if paper_dir.exists() and not any(paper_dir.iterdir()):                                                                                                                                                     
            paper_dir.rmdir()                                                                                                                                                                                       
        raise error                                                                                                                                                                                                 
                                                                                                                                                                                                                    
    has_tex = extract_source(source_path, paper_dir)                                                                                                                                                                
                                                                                                                                                                                                                    
    if not has_tex:                                                                                                                                                                                                 
        shutil.rmtree(paper_dir)
        return False                                                                                                                                                                                                
                                                                                                                                                                                                                    
    return True                                                                                                                                                                                                     
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def fetch_papers(max_override=None, dry_run=False):
    """Search arXiv and download LaTeX sources."""                                                                                                                                                                  
    config = load_config()                                                                                                                                                                                          
    arxiv_config = config["arxiv"]                                                                                                                                                                                  
                                                                                                                                                                                                                    
    RAW_DIR.mkdir(parents=True, exist_ok=True)                                                                                                                                                                      
    METADATA_DIR.mkdir(parents=True, exist_ok=True)                                                                                                                                                                 
                                                                                                                                                                                                                    
    manifest_path = METADATA_DIR / "manifest.json"                                                                                                                                                                  
    all_metadata, seen_ids = _load_manifest(manifest_path)                                                                                                                                                          
                                                                                                                                                                                                                    
    max_per_query = max_override or arxiv_config["max_results_per_query"]                                                                                                                                           
    client = arxiv.Client()                                                                                                                                                                                         
                                                                                                                                                                                                                    
    stats = {"fetched": 0, "skipped": 0, "failed": 0, "no_tex": 0}                                                                                                                                                  
                                                                                                                                                                                                                    
    for query in arxiv_config["queries"]:                                                                                                                                                                           
        print(f"\n--- {query} ---")
                                                                                                                                                                                                                    
        search = arxiv.Search(                                                                                                                                                                                      
            query=query,                                                                                                                                                                                            
            max_results=max_per_query,                                                                                                                                                                              
            sort_by=arxiv.SortCriterion.Relevance,                                                                                                                                                                  
        )                                                                                                                                                                                                           
                                                                                                                                                                                                                    
        for result in client.results(search):                                                                                                                                                                       
            arxiv_id = result.entry_id.split("/abs/")[-1]                                                                                                                                                           
                                                                                                                                                                                                                    
            if arxiv_id in seen_ids:                                                                                                                                                                                
                stats["skipped"] += 1                                                                                                                                                                               
                continue                                                                                                                                                                                            
            seen_ids.add(arxiv_id)                                                                                                                                                                                  
                                                                                                                                                                                                                    
            title_short = result.title[:70].replace("\n", " ")                                                                                                                                                      
            print(f"  {arxiv_id}: {title_short}")                                                                                                                                                                   
                                                                                                                                                                                                                    
            if dry_run:                                                                                                                                                                                             
                stats["fetched"] += 1                                                                                                                                                                               
                continue                                                                                                                                                                                            
                                                                                                                                                                                                                    
            paper_dir = RAW_DIR / arxiv_id.replace("/", "_")                                                                                                                                                        
                                                                                                                                                                                                                    
            try:                                                                                                                                                                                                    
                success = download_paper(result, paper_dir)
            except Exception as error:                                                                                                                                                                              
                print(f"    [ERROR] {error}")                                                                                                                                                                       
                stats["failed"] += 1                                                                                                                                                                                
                continue                                                                                                                                                                                            
                                                                                                                                                                                                                    
            if not success:                                                                                                                                                                                         
                print(f"    [WARN] no .tex files found")                                                                                                                                                            
                stats["no_tex"] += 1                                                                                                                                                                                
                continue                                                                                                                                                                                            
                                                                                                                                                                                                                    
            metadata = {                                                                                                                                                                                            
                "arxiv_id": arxiv_id,
                "title": result.title,                                                                                                                                                                              
                "authors": [author.name for author in result.authors],                                                                                                                                              
                "abstract": result.summary,                                                                                                                                                                         
                "categories": result.categories,                                                                                                                                                                    
                "published": result.published.isoformat(),                                                                                                                                                          
                "updated": result.updated.isoformat() if result.updated else None,                                                                                                                                  
                "pdf_url": result.pdf_url,                                                                                                                                                                          
                "source_dir": str(paper_dir),                                                                                                                                                                       
            }                                                                                                                                                                                                       
                                                                                                                                                                                                                    
            with open(paper_dir / "metadata.json", "w") as f:                                                                                                                                                       
                json.dump(metadata, f, indent=2, ensure_ascii=False)                                                                                                                                                
                                                                                                                                                                                                                    
            all_metadata.append(metadata)                                                                                                                                                                           
            _save_manifest(manifest_path, all_metadata)                                                                                                                                                             
            stats["fetched"] += 1                                                                                                                                                                                   
                                                                                                                                                                                                                    
    print(f"\nDone. Fetched: {stats['fetched']}, "                                                                                                                                                                  
        f"Skipped: {stats['skipped']}, "                                                                                                                                                                          
        f"Failed: {stats['failed']}, "                                                                                                                                                                            
        f"No .tex: {stats['no_tex']}, "                                                                                                                                                                           
        f"Total: {len(all_metadata)}")                                                                                                                                                                            
                                                                                                                                                                                                                    
    return all_metadata                                                                                                                                                                                             
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def _load_manifest(manifest_path):
    if manifest_path.exists():                                                                                                                                                                                      
        with open(manifest_path) as f:                                                                                                                                                                              
            existing = json.load(f)                                                                                                                                                                                 
        seen_ids = {paper["arxiv_id"] for paper in existing}                                                                                                                                                        
        print(f"Resuming — {len(seen_ids)} papers already downloaded")                                                                                                                                              
        return existing, seen_ids                                                                                                                                                                                   
    return [], set()                                                                                                                                                                                                
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def _save_manifest(manifest_path, metadata_list):                                                                                                                                                                   
    with open(manifest_path, "w") as f:                                                                                                                                                                             
        json.dump(metadata_list, f, indent=2, ensure_ascii=False)                                                                                                                                                   
                                                                                                                                                                                                                    
